on:
  workflow_dispatch:

jobs:
  dispatch-tests: # This job will trigger the plugin tests workflow in the other repositories
    strategy:
      matrix:
        repo: ['CUQI-DTU/CUQIpy-PyTorch']
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch plugin tests after publishing to PyPI
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: run-plugin-tests
          client-payload: '{event_name: ${{ github.event_name }}'